### ISSUE TITLE
How do I run this with node.js? 

### ISSUE THREAD

**Issue by Tzikas** [JMPerez/spotify-search#1]
I cloned it, and ran `bower install spotify-search` and `http-server`

**Comment by JMPerez** [comment]
Pull and try running it using `http-server -p 5000 .`. In any case, this is an old project and Polymer has changed a lot since.

**Comment by Tzikas** [comment]
Thanks anyways.  I'm getting not found resources 404 when I http-server -p
5000 inside the demo and the root folder.  In the demo folder, I get the
text, but no search box.

On Thu, Jan 19, 2017 at 2:30 AM, José Manuel Pérez <notifications@github.com

**Comment by Tzikas** [comment]
But the files do exists in the bower_components directory...

**Comment by JMPerez** [comment]
Have you tried accessing http://localhost:5000/demo/ when running `http-server -p 5000 .` from the root?

**Comment by Tzikas** [comment]
Yes it worked now.  I didn't navigate to the demo directory.  Sorry for the
silly question but thank you very much :)
